# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-11-23
openapi: 3.1.1
info:
  title: Content management system API
  version: 0.1.0

paths:
  /entries:
    get:
      summary: Get entry summaries
      operationId: getSummaries
      parameters:
        - name: model
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EntrySummary"
    post:
      operationId: postEntry
      requestBody:
        description: OK
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewEntryInputDto"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identitiy"

  /entries/{id}:
    get:
      summary: Returns single entry
      operationId: getEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: JSON
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Entry"
        "404":
          description: Not found

    put:
      summary: Replace entry
      operationId: putEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: OK
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EntryInputDto"
      responses:
        "204":
          description: OK

    delete:
      summary: Delete entry
      operationId: deleteEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: OK
  /resources:
    get:
      summary: Retruns resources
      operationId: getResources
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Resource"

  /resources/{id}:
    get:
      summary: Return resource
      operationId: getResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"

        "404":
          description: Not found
  /models:
    get:
      summary: Return models
      operationId: getModels
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Model"

  /models/{id}:
    get:
      summary: Return model
      operationId: getModel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        "404":
          description: Error

components:
  schemas:
    NodeJson:
      oneOf:
        - $ref: "#/components/schemas/StringNodeJson"
        - $ref: "#/components/schemas/NumberNodeJson"
        - $ref: "#/components/schemas/BooleanNodeJson"
        - $ref: "#/components/schemas/DatetimeNodeJson"
        - $ref: "#/components/schemas/ListNodeJson"
        - $ref: "#/components/schemas/MapNodeJson"
        - $ref: "#/components/schemas/ReferenceNodeJson"
        - $ref: "#/components/schemas/AssetNodeJson"
    StringNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - string
        value:
          type: string
      required:
        - type
        - value
      additionalProperties: false
    NumberNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - number
        value:
          type: number
      required:
        - type
        - value
      additionalProperties: false
    BooleanNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - boolean
        value:
          type: boolean
      required:
        - type
        - value
      additionalProperties: false
    DatetimeNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - datetime
        value:
          type: string
      required:
        - type
        - value
      additionalProperties: false
    ListNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - list
        value:
          type: array
          # items:
          #   $ref: "#/components/schemas/NodeJson"
      required:
        - type
        - value
      additionalProperties: false
    MapNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - map
        value:
          type: object
      required:
        - type
        - value
      additionalProperties: false
    ReferenceNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - reference
        value:
          type: string
      required:
        - type
        - value
      additionalProperties: false
    AssetNodeJson:
      type: object
      properties:
        type:
          type: string
          enum:
            - asset
        value:
          type: string
      required:
        - type
        - value
      additionalProperties: false

    EntryInputDto:
      type: object
      properties:
        name:
          type: string
        node:
          $ref: "#/components/schemas/NodeJson"
      required:
        - name
        - node
      additionalProperties: false

    NewEntryInputDto:
      type: object
      properties:
        name:
          type: string
        model:
          type: string
        node:
          $ref: "#/components/schemas/NodeJson"
      required:
        - string
        - model
        - node

    EntrySummary:
      type: object
      properties:
        id:
          type: string
        model:
          type: string
        name:
          type: string
      required:
        - id
        - model
        - name
      unevaluatedProperties: false

    Identitiy:
      type: object
      properties:
        id:
          type: string
      required:
        - id
      additionalProperties: false

    Resource:
      type: object
      properties:
        id:
          type: string
        model:
          type: string
      required:
        - id
        - model
      additionalProperties: false

    Model:
      oneOf:
        - $ref: "#/components/schemas/StringModel"
        - $ref: "#/components/schemas/NumberModel"
        - $ref: "#/components/schemas/BooleanModel"
        - $ref: "#/components/schemas/DatetimeModel"
        - $ref: "#/components/schemas/ReferenceModel"
        - $ref: "#/components/schemas/MapModel"
        - $ref: "#/components/schemas/ListModel"
        - $ref: "#/components/schemas/UnionModel"

    StringModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["string"]
      required:
        - type

    NumberModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["number"]
      required:
        - type

    BooleanModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["boolean"]
      required:
        - type

    DatetimeModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["datetime"]
      required:
        - type

    ReferenceModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["reference"]

        model:
          type: string
      required:
        - type
        - model

    MapModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["map"]

        props:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Model"
        required:
          type: array
          items:
            type: string
      required:
        - type
        - props
        - required

    ListModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["list"]

        item:
          $ref: "#/components/schemas/Model"
      required:
        - type
        - item

    UnionModel:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseModel"
      properties:
        type:
          enum: ["union"]

        variants:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Model"
      required:
        - type
        - variants

    BaseModel:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        # - id
        - title
        - description
      unevaluatedProperties: false

    Entry:
      type: object
      allOf:
        - $ref: "#/components/schemas/EntrySummary"
      properties:
        contents:
          $ref: "#/components/schemas/Contents"
      required:
        - contents
      unevaluatedProperties: false

    Contents:
      oneOf:
        - $ref: "#/components/schemas/StringContents"
        - $ref: "#/components/schemas/NumberContents"
        - $ref: "#/components/schemas/BooleanContents"
        - $ref: "#/components/schemas/DatetimeContents"
        - $ref: "#/components/schemas/MapContents"
        - $ref: "#/components/schemas/ListContents"
        - $ref: "#/components/schemas/UnionContents"
        - $ref: "#/components/schemas/ReferenceContents"

    StringContents:
      type: string
    NumberContents:
      type: number
    BooleanContents:
      type: boolean
    DatetimeContents:
      type: string
    MapContents:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Contents"
    ListContents:
      type: array
      items:
        $ref: "#/components/schemas/Contents"
    UnionContents:
      type: array
      prefixItems:
        - type: string
        - $ref: "#/components/schemas/Contents"
      unevaluatedItems: false
    ReferenceContents:
      type: string
