# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2025-11-23
openapi: 3.1.1
info:
  title: Content management system API
  version: 0.1.0

paths:
  /entries:
    get:
      summary: Get entry summaries
      operationId: getSummaries
      parameters:
        - name: model
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EntrySummaryResponse"
    post:
      operationId: postEntry
      requestBody:
        description: OK
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EntryInput"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identitiy"
        "400":
          $ref: "#/components/responses/ErrorResponse"
        "409":
          $ref: "#/components/responses/ErrorResponse"

        "422":
          description: Validation failure
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ValidationProblemDetails"
        "500":
          $ref: "#/components/responses/ErrorResponse"

  /entries/{id}:
    get:
      summary: Returns single entry
      operationId: getEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: JSON
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryResponse"
        "404":
          $ref: "#/components/responses/ErrorResponse"

    put:
      summary: Replace entry
      operationId: putEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: OK
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEntryInput"
      responses:
        "204":
          description: OK

    delete:
      summary: Delete entry
      operationId: deleteEntry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: OK
  /schemas:
    get:
      summary: Retruns schemas
      operationId: getSchemas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SchemaResponse"

  /schemas/{id}:
    get:
      summary: Return schema
      operationId: getSchema
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaResponse"

        "404":
          $ref: "#/components/responses/ErrorResponse"
  /models:
    get:
      summary: Return models
      operationId: getModels
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ModelResponse"

  /models/{id}:
    get:
      summary: Return model
      operationId: getModel
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelResponse"
        "404":
          $ref: "#/components/responses/ErrorResponse"

components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: URI reference that identifies the problem type.

        title:
          type: string
          description: Short human-readable summary of the problem type.

        status:
          type: integer
          description: HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 100
          maximum: 599

        detail:
          type: string
          description: Human-readable explanation specific to this occurrence of the problem.

        instance:
          type: string
          format: uri-reference
          description: URI reference that identifies the specific occurrence of the problem.

      required:
        - type
        - title
        - status
        - detail
        - instance

    ValidationProblemDetails:
      allOf:
        - $ref: "#/components/schemas/ProblemDetails"
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
      required:
        - errors

    ValidationError:
      type: object
      properties:
        pointer:
          type: string
        title:
          type: string
      required:
        - pointer
        - title

    UpdateEntryInput:
      type: object
      properties:
        name:
          type: string
        contents:
          $ref: "#/components/schemas/Contents"
      required:
        - name
        - contents

    EntryInput:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        model:
          type: string
          minLength: 1
        contents:
          $ref: "#/components/schemas/Contents"
      required:
        - name
        - model
        - contents

    EntrySummaryResponse:
      type: object
      properties:
        id:
          type: string
        model:
          type: object
          properties:
            id:
              type: string
          required:
            - id
        name:
          type: string
      required:
        - id
        - model
        - name
      unevaluatedProperties: false

    Identitiy:
      type: object
      properties:
        id:
          type: string
      required:
        - id
      additionalProperties: false

    ModelResponse:
      type: "object"
      properties:
        id:
          type: string
        schema:
          type: object
          properties:
            id:
              type: string
          required:
            - id
        type:
          enum: [collection, singleton]
      required:
        - id
        - schema
        - type

    SchemaReference:
      type: object
      properties:
        id:
          type: string
      required:
        - id

    SchemaResponse:
      oneOf:
        - $ref: "#/components/schemas/StringSchemaResponse"
        - $ref: "#/components/schemas/NumberSchemaResponse"
        - $ref: "#/components/schemas/BooleanSchemaResponse"
        - $ref: "#/components/schemas/TemporalSchemaResponse"
        - $ref: "#/components/schemas/ReferenceSchemaResponse"
        - $ref: "#/components/schemas/MapSchemaResponse"
        - $ref: "#/components/schemas/ListSchemaResponse"
        - $ref: "#/components/schemas/UnionSchemaResponse"

    StringSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["string"]
      required:
        - type

    NumberSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["number"]
      required:
        - type

    BooleanSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["boolean"]
      required:
        - type

    TemporalSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["temporal"]
      required:
        - type

    ReferenceSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["reference"]

        schema:
          $ref: "#/components/schemas/SchemaReference"
      required:
        - type
        - schema

    MapSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["map"]

        properties:
          type: object

          additionalProperties:
            type: object
            properties:
              required:
                type: boolean
              schema:
                $ref: "#/components/schemas/SchemaReference"

            required:
              - required
              - schema

      required:
        - type
        - properties

    ListSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["list"]
        item:
          $ref: "#/components/schemas/SchemaReference"

      required:
        - type
        - item

    UnionSchemaResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/BaseSchemaResponse"
      properties:
        type:
          enum: ["union"]
        schemas:
          type: array
          items:
            $ref: "#/components/schemas/SchemaReference"

      required:
        - type
        - schemas

    BaseSchemaResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
      unevaluatedProperties: false

    EntryResponse:
      type: object
      allOf:
        - $ref: "#/components/schemas/EntrySummaryResponse"
      properties:
        contents:
          $ref: "#/components/schemas/Contents"
      required:
        - contents
      unevaluatedProperties: false

    Contents:
      oneOf:
        - $ref: "#/components/schemas/StringContents"
        - $ref: "#/components/schemas/NumberContents"
        - $ref: "#/components/schemas/BooleanContents"
        - $ref: "#/components/schemas/MapContents"
        - $ref: "#/components/schemas/ListContents"

    StringContents:
      type: string
    NumberContents:
      type: number
    BooleanContents:
      type: boolean
    DatetimeContents:
      type: string
    MapContents:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Contents"
    ListContents:
      type: array
      items:
        $ref: "#/components/schemas/Contents"

  responses:
    ErrorResponse:
      description: Error
      content:
        application:json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
